INSERT INTO TSEG_OPERACION (   OPE_NOMBRE, OPE_ID, OPE_CODIGO) VALUES ('Insertar', sSEG_OPERACION.nextval,'I');
INSERT INTO TSEG_OPERACION (   OPE_NOMBRE, OPE_ID, OPE_CODIGO) VALUES ('Obtener', sSEG_OPERACION.nextval,'O');
INSERT INTO TSEG_OPERACION (   OPE_NOMBRE, OPE_ID, OPE_CODIGO) VALUES ('Actualizar', sSEG_OPERACION.nextval,'A');
INSERT INTO TSEG_OPERACION (   OPE_NOMBRE, OPE_ID, OPE_CODIGO) VALUES ('Borrar', sSEG_OPERACION.nextval,'B');