--Creacion del sistema
INSERT INTO TSEG_SISTEMA (   SIS_NOMBRE,  SIS_ID,     SIS_CODIGO) 
VALUES ( 'SISTEMA UNO', SSEG_SISTEMA.NEXTVAL,'SIS001');
--Creacion de Modulos
INSERT INTO TSEG_MODULO (   SIS_ID, MOD_NOMBRE_MENU, MOD_NOMBRE,    MOD_ID, MOD_CODIGO) 
VALUES ( (select sis_id from TSEG_SISTEMA where sis_codigo='SIS001'),
    'CONFIGURACIÓN','CONFIGURACIÓN', sSEG_MODULO.NEXTVAL,'MODCONFIG' );
--creacion de funcionalidades
INSERT INTO TSEG_FUNCIONALIDAD (   MOD_ID, FUN_URL, FUN_PARAMETROS,    FUN_NOMBRE_MENU, FUN_NOMBRE, FUN_ID,    FUN_ESTADO, FUN_CODIGO) 
VALUES ( (select MOD_id from TSEG_MODULO where MOD_codigo='MODCONFIG'),
 '/', '', 'ASIGNACION DE PERMISOS', 'ASIGNACION DE PERMISOS', sSEG_FUNCIONALIDAD.NEXTVAL,
 (select ITE.itE_id from tadm_catalogo cat, tadm_item_catalogo ite where cat.cat_id=ite.cat_id and cat.cat_codigo='FUNCIONALIDADESTADO' and ite.ite_codigo='ACTIVO'),
 'FUNASIGPERMI');
 INSERT INTO TSEG_FUNCIONALIDAD (   MOD_ID, FUN_URL, FUN_PARAMETROS,    FUN_NOMBRE_MENU, FUN_NOMBRE, FUN_ID,    FUN_ESTADO, FUN_CODIGO) 
VALUES ( (select MOD_id from TSEG_MODULO where MOD_codigo='MODCONFIG'),
 '/', '', 'ROLES', 'ROLES', sSEG_FUNCIONALIDAD.NEXTVAL,
 (select ITE.itE_id from tadm_catalogo cat, tadm_item_catalogo ite where cat.cat_id=ite.cat_id and cat.cat_codigo='FUNCIONALIDADESTADO' and ite.ite_codigo='ACTIVO'),
 'FUNROLES');
 
 --OPERACIONES
 INSERT INTO TSEG_FUN_OPERACION (OPE_ID, FUN_ID, FOP_ID) 
SELECT OPE_ID, FUN_ID,sSEG_FUN_OPERACION.NEXTVAL FROM  TSEG_FUNCIONALIDAD FUN, TSEG_OPERACION OPE WHERE FUN_CODIGO='FUNASIGPERMI' AND OPE_CODIGO IN ('I','O','A','B');

 INSERT INTO TSEG_FUN_OPERACION (OPE_ID, FUN_ID, FOP_ID) 
SELECT OPE_ID, FUN_ID,sSEG_FUN_OPERACION.NEXTVAL FROM  TSEG_FUNCIONALIDAD FUN, TSEG_OPERACION OPE WHERE FUN_CODIGO='FUNROLES' AND OPE_CODIGO IN ('I','O','A','B');
 
  
  
 
    